### ISSUE TITLE
Minecraft Crash - Forge 1.8

### ISSUE THREAD

**Issue by TnTGamesTV** [unaussprechlich/HudPixelExtended#10]
So basicly:
As Minecraft ist "booting", everything is fine. But if I connect to Hypixel, it crashes. 
NoSuchFieldException!

`---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 16.12.16 18:51
Description: Unexpected error

java.lang.NoSuchFieldError: field_181705_e
	at net.unaussprechlich.managedgui.lib.util.RenderUtils.renderBoxWithColor(RenderUtils.java:154)
	at net.unaussprechlich.managedgui.lib.util.RenderUtils.renderBoxWithHudBackground(RenderUtils.java:94)
	at net.unaussprechlich.managedgui.lib.util.RenderUtils.renderItemStackHudBackground(RenderUtils.java:82)
	at com.palechip.hudpixelmod.extended.gui.ArmorHud.onRender(ArmorHud.kt:87)
	at com.palechip.hudpixelmod.extended.HudPixelExtendedEventHandler$$Lambda$6/641090152.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.palechip.hudpixelmod.extended.HudPixelExtendedEventHandler.onRenderTick(HudPixelExtendedEventHandler.java:305)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_20_HudPixelExtendedEventHandler_onRenderTick_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:858)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:190)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1059)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.unaussprechlich.managedgui.lib.util.RenderUtils.renderBoxWithColor(RenderUtils.java:154)
	at net.unaussprechlich.managedgui.lib.util.RenderUtils.renderBoxWithHudBackground(RenderUtils.java:94)
	at net.unaussprechlich.managedgui.lib.util.RenderUtils.renderItemStackHudBackground(RenderUtils.java:82)
	at com.palechip.hudpixelmod.extended.gui.ArmorHud.onRender(ArmorHud.kt:87)
	at com.palechip.hudpixelmod.extended.HudPixelExtendedEventHandler$$Lambda$6/641090152.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.palechip.hudpixelmod.extended.HudPixelExtendedEventHandler.onRenderTick(HudPixelExtendedEventHandler.java:305)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_20_HudPixelExtendedEventHandler_onRenderTick_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:858)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:190)

-- Affected level --
Details:
	Level name: MpServer
	All players: 3 total; [EntityPlayerSP['TnTGamesTV'/49851, l='MpServer', x=-2561,75, y=55,00, z=744,07], EntityOtherPlayerMP['c1mrz0338b'/166, l='MpServer', x=-2530,50, y=51,50, z=720,50], EntityOtherPlayerMP['33yc0c6p13'/162, l='MpServer', x=-2530,50, y=51,50, z=768,50]]
	Chunk stats: MultiplayerChunkCache: 25, 25
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: -2562,00,55,00,744,00 - World: (-2562,55,744), Chunk: (at 14,3,8 in -161,46; contains blocks -2576,0,736 to -2561,255,751), Region: (-6,1; contains chunks -192,32 to -161,63, blocks -3072,0,512 to -2561,255,1023)
	Level time: 1045465674 game time, 264500 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 49 total; [EntityPlayerSP['TnTGamesTV'/49851, l='MpServer', x=-2561,75, y=55,00, z=744,07], EntityVillager['Dorfbewohner'/1, l='MpServer', x=-2573,38, y=67108863,97, z=773,31], EntityArmorStand['Rüstungsständer'/2, l='MpServer', x=-2550,31, y=48,59, z=728,78], EntityArmorStand['Rüstungsständer'/3, l='MpServer', x=-2544,81, y=49,59, z=729,09], EntityArmorStand['Rüstungsständer'/4, l='MpServer', x=-2544,50, y=49,59, z=734,84], EntityArmorStand['Rüstungsständer'/5, l='MpServer', x=-2548,88, y=49,59, z=738,78], EntityItemFrame['entity.ItemFrame.name'/6, l='MpServer', x=-2553,50, y=55,50, z=776,97], EntityItemFrame['entity.ItemFrame.name'/7, l='MpServer', x=-2552,50, y=55,50, z=776,97], EntityItemFrame['entity.ItemFrame.name'/8, l='MpServer', x=-2551,50, y=55,50, z=776,97], EntityItemFrame['entity.ItemFrame.name'/9, l='MpServer', x=-2547,50, y=54,50, z=776,97], EntityItemFrame['entity.ItemFrame.name'/10, l='MpServer', x=-2548,50, y=54,50, z=776,97], EntityItemFrame['entity.ItemFrame.name'/11, l='MpServer', x=-2549,50, y=54,50, z=776,97], EntityItemFrame['entity.ItemFrame.name'/12, l='MpServer', x=-2545,50, y=55,50, z=776,97], EntityItemFrame['entity.ItemFrame.name'/13, l='MpServer', x=-2544,50, y=55,50, z=776,97], EntityItemFrame['entity.ItemFrame.name'/14, l='MpServer', x=-2545,50, y=52,50, z=776,97], EntityItemFrame['entity.ItemFrame.name'/15, l='MpServer', x=-2551,50, y=52,50, z=776,97], EntityArmorStand['Rüstungsständer'/16, l='MpServer', x=-2532,94, y=50,09, z=728,66], EntityArmorStand['Rüstungsständer'/17, l='MpServer', x=-2538,50, y=49,59, z=729,34], EntityArmorStand['Rüstungsständer'/18, l='MpServer', x=-2543,59, y=49,59, z=739,22], EntityItemFrame['entity.ItemFrame.name'/19, l='MpServer', x=-2543,50, y=55,50, z=776,97], EntityOtherPlayerMP['c1mrz0338b'/166, l='MpServer', x=-2530,50, y=51,50, z=720,50], EntityOtherPlayerMP['33yc0c6p13'/162, l='MpServer', x=-2530,50, y=51,50, z=768,50], EntityArmorStand['§e§lRECHTSKLICK§r'/164, l='MpServer', x=-2530,50, y=53,47, z=768,50], EntityZombie['§8Lv§7001 §rtrouducu2'/49445, l='MpServer', x=-2540,28, y=50,00, z=733,00], EntityArmorStand['§bDer Delivery Man§r'/165, l='MpServer', x=-2530,50, y=53,75, z=768,50], EntityOtherPlayerMP['c1mrz0338b'/166, l='MpServer', x=-2530,50, y=51,50, z=720,50], EntityArmorStand['§e§lRECHTSKLICK§r'/168, l='MpServer', x=-2530,50, y=53,47, z=720,50], EntityArmorStand['§bDer Delivery Man§r'/169, l='MpServer', x=-2530,50, y=53,75, z=720,50], EntityArmorStand['§bMystery Vault'/170, l='MpServer', x=-2538,50, y=53,38, z=736,50], EntitySnowman['Schneegolem'/-2147483605, l='MpServer', x=-2541,25, y=50,00, z=734,28], EntityArmorStand['§e§lRECHTSKLICK'/171, l='MpServer', x=-2538,50, y=53,09, z=736,50], EntityArmorStand['§bMystery Vault'/172, l='MpServer', x=-2538,50, y=53,38, z=752,50], EntityArmorStand['§e§lRECHTSKLICK'/173, l='MpServer', x=-2538,50, y=53,09, z=752,50], EntityVillager['Dorfbewohner'/174, l='MpServer', x=-2557,50, y=52,00, z=747,50], EntityArmorStand['§e§lRECHTSKLICK§r'/175, l='MpServer', x=-2557,50, y=54,16, z=747,50], EntityArmorStand['§bQuest Master§r'/176, l='MpServer', x=-2557,50, y=54,47, z=747,50], EntityArmorStand['Rüstungsständer'/177, l='MpServer', x=-2563,50, y=39,53, z=754,50], EntityBat['Fledermaus'/178, l='MpServer', x=-2530,50, y=52,84, z=720,50], EntityBat['Fledermaus'/179, l='MpServer', x=-2530,50, y=52,84, z=768,50], EntityArmorStand['§c1 Lieferung!§r'/49852, l='MpServer', x=-2530,50, y=54,06, z=768,50], EntityArmorStand['§c1 Lieferung!§r'/49853, l='MpServer', x=-2530,50, y=54,06, z=720,50], EntityOtherPlayerMP['33yc0c6p13'/162, l='MpServer', x=-2530,50, y=51,50, z=768,50], EntityWither['§aRanks§7, §bBoosters§7, §eMystery Boxes §7& more! §r? §6§lSTORE.HYPIXEL.NET§r'/-1234, l='MpServer', x=-2528,78, y=55,00, z=744,06], EntityWolf['§8Lv§7024 §r§4§lOs§cc§8§lar'/49491, l='MpServer', x=-2545,91, y=50,00, z=739,84], EntityWolf['§8Lv§7001 §r§4§lDEVILMAN'/49631, l='MpServer', x=-2544,81, y=50,00, z=735,13], EntityArmorStand['§e§lParkour Challenge'/108, l='MpServer', x=-2577,50, y=46,34, z=724,50], EntityArmorStand['§a§lStart'/109, l='MpServer', x=-2577,50, y=46,00, z=724,50], EntityArmorStand['§e§lCheckpoint'/112, l='MpServer', x=-2564,50, y=20,34, z=758,50], EntityArmorStand['§b§l#1'/113, l='MpServer', x=-2564,50, y=20,00, z=758,50]]
	Retry entities: 0 total; []
	Server brand: BungeeCord (Hypixel) <- vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:351)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2502)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:374)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 191146448 bytes (182 MB) / 363225088 bytes (346 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.4.1563 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.4.1563.jar) 
	UCHIJA	Forge{11.14.4.1563} [Minecraft Forge] (forge-1.8-11.14.4.1563.jar) 
	UCHIJA	hudpixel{3.0} [HudPixel Reloaded] (HudPixelReloaded-1.8.9-v3-3.2.7.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '3.3.0' Renderer: 'Quadro FX 1800M/PCIe/SSE2'
	Launched Version: 1.8-forge1.8-11.14.4.1563
	LWJGL: 2.9.1
	OpenGL: Quadro FX 1800M/PCIe/SSE2 GL version 3.3.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: Deutsch (Deutschland)
	Profiler Position: N/A (disabled)`

**Comment by unaussprechlich** [comment]
You are using Minecraft 1.8, you need 1.8.9 to run HudPixel. Download it here http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.8.9.html

**Comment by TnTGamesTV** [comment]
Okay. Will install it in the next days. Can't wait to see what this mod has to offer.

**Comment by unaussprechlich** [comment]
Why du you run a Nvidia Quadro video card from 2010 :D that could also be a problem. Have you updated your drivers ?
Edit: gerade gesehen, dass du deutsch bist ;)

**Comment by TnTGamesTV** [comment]
Deutsch. :D 
Naja. Wegen der Graka. Die macht keine Probleme. Forge geupdated, 1.8.9 drauf, boot und läuft. 

👍 

~TnTGamesTV
